// Strata lore and content tables: biomes (one per tier), the kinds of places in
// them, creatures and their tempers, relics with their stories.
//
// The world: long ago a smith-god split the world with a sword. The layers came
// apart like a cut pie and hang over the abyss, one under another. People,
// dwarves and beasts live in the tiers. At the bottom of every Cut stand the
// Gates, sealed with three Seals. The hero goes down.

import { B } from './world.js';

// ---- connector styles: how stairs, bridges and ledges between places are built
export const PATHS = {
    plank: { floor: B.PLANK, stair: B.PLANK, support: B.TIMBER, rail: 'rope', lamp: 'lantern' },
    stone: { floor: B.COBBLE, stair: B.BRICK, support: B.BRICK, rail: 'stone', lamp: 'torch' },
    rock: { floor: B.ROCK, stair: B.ROCK, support: B.ROCK, rail: null, lamp: 'torch' },
    moss: { floor: B.MOSS, stair: B.ROCK, support: B.ROCK, rail: null, lamp: 'glowworm' },
    metal: { floor: B.METAL, stair: B.METAL, support: B.BASALT, rail: 'iron', lamp: 'brazier' },
    root: { floor: B.BARK, stair: B.BARK, support: B.BARK, rail: null, lamp: 'sap' },
    marble: { floor: B.MARBLE, stair: B.MARBLE, support: B.BRICK, rail: 'stone', lamp: 'candle' },
    crypt: { floor: B.CRYPT, stair: B.CRYPT, support: B.CRYPT, rail: 'iron', lamp: 'candle' },
    crystal: { floor: B.ROCK, stair: B.ROCK, support: B.ROCK, rail: null, lamp: 'crystal' },
};

// ---- places. shape: rect or blob; walls: built (back walls + parapet), rock, none
export const PLACES = {
    meadow: { shape: 'blob', size: [9, 14], walls: 'none', under: 5 },
    house: { shape: 'rect', size: [6, 9], walls: 'built', wallH: [4, 4], under: 3 },
    square: { shape: 'rect', size: [7, 11], walls: 'none', under: 4 },
    garden: { shape: 'rect', size: [6, 9], walls: 'fence', under: 3 },
    ruinhall: { shape: 'rect', size: [7, 11], walls: 'ruin', wallH: [2, 5], under: 4 },
    graveyard: { shape: 'blob', size: [8, 12], walls: 'none', under: 4 },
    gallery: { shape: 'blob', size: [8, 13], walls: 'rock', wallH: [3, 5], under: 5 },
    storage: { shape: 'rect', size: [6, 8], walls: 'built', wallH: [3, 4], under: 3 },
    camp: { shape: 'blob', size: [6, 8], walls: 'rock', wallH: [2, 4], under: 3 },
    pool: { shape: 'blob', size: [9, 13], walls: 'rock', wallH: [3, 5], under: 5 },
    mosscave: { shape: 'blob', size: [8, 12], walls: 'rock', wallH: [3, 6], under: 5 },
    grove: { shape: 'blob', size: [9, 13], walls: 'rock', wallH: [2, 4], under: 5 },
    geode: { shape: 'blob', size: [8, 12], walls: 'rock', wallH: [3, 6], under: 5 },
    cryptHall: { shape: 'rect', size: [7, 11], walls: 'built', wallH: [4, 5], under: 4 },
    chapel: { shape: 'rect', size: [7, 9], walls: 'built', wallH: [5, 5], under: 4 },
    forgeHall: { shape: 'rect', size: [8, 12], walls: 'built', wallH: [4, 5], under: 4 },
    lavaCave: { shape: 'blob', size: [9, 13], walls: 'rock', wallH: [3, 5], under: 5 },
    stacks: { shape: 'rect', size: [8, 11], walls: 'built', wallH: [5, 5], under: 4 },
    reading: { shape: 'rect', size: [6, 9], walls: 'built', wallH: [4, 5], under: 3 },
    rootCave: { shape: 'blob', size: [9, 13], walls: 'rock', wallH: [3, 5], under: 5 },
    gateHall: { shape: 'rect', size: [11, 13], walls: 'built', wallH: [6, 6], under: 5 },
    antechamber: { shape: 'rect', size: [7, 9], walls: 'built', wallH: [4, 5], under: 4 },
};

// ---- biomes, one per tier
export const BIOMES = {
    village: {
        name: 'Деревня над Разрезом',
        outdoor: true,
        floor: B.GRASS, floor2: B.DIRT, under: B.DIRT, under2: B.ROCK, wall: B.TIMBER, inner: B.WALLPAPER, rim: B.ROCK,
        path: 'plank',
        places: [['meadow', 4], ['house', 3], ['square', 2], ['garden', 2]],
        creatures: [['pigeon', 3], ['sheep', 2], ['slime', 2], ['wolf', 2]],
        elite: { kind: 'wolf', name: 'Вожак Серой Стаи' },
        emitters: ['leaf', 'firefly'],
        fog: 0xcfe6ef, ambient: 1,
        relics: ['vane', 'spoon', 'map'],
    },
    ruins: {
        name: 'Руины Старой Стражи',
        outdoor: true,
        floor: B.GRASS, floor2: B.MOSSBRICK, under: B.DIRT, under2: B.ROCK, wall: B.MOSSBRICK, inner: B.BRICK, rim: B.MOSSBRICK,
        path: 'stone',
        places: [['meadow', 2], ['ruinhall', 4], ['graveyard', 3], ['square', 1]],
        creatures: [['crow', 3], ['slime', 2], ['skeleton', 2], ['wolf', 1]],
        elite: { kind: 'skeleton', name: 'Капитан Бессонной Стражи' },
        emitters: ['leaf', 'firefly'],
        fog: 0xd8e2dd, ambient: 0.95,
        relics: ['helm', 'horn', 'oath'],
    },
    mine: {
        name: 'Штольни Кирки',
        floor: B.ROCK, floor2: B.PLANK, under: B.ROCK, under2: B.ORE, wall: B.ROCK, inner: B.TIMBER, rim: B.ROCK,
        path: 'plank',
        places: [['gallery', 4], ['storage', 2], ['camp', 1], ['mosscave', 1]],
        creatures: [['rat', 3], ['kobold', 3], ['golem', 2]],
        elite: { kind: 'kobold', name: 'Старший Штейгер' },
        emitters: ['dust'],
        fog: 0x4a4038, ambient: 0.55,
        relics: ['helmet', 'pick', 'token'],
    },
    grotto: {
        name: 'Затопленный Грот',
        floor: B.MOSS, floor2: B.SAND, under: B.ROCK, under2: B.MOSS, wall: B.ROCK, inner: B.ROCK, rim: B.ROCK,
        path: 'moss',
        places: [['pool', 4], ['mosscave', 3], ['camp', 1]],
        creatures: [['frog', 3], ['crab', 2], ['drowned', 3], ['bat', 1]],
        elite: { kind: 'drowned', name: 'Лодочник Мирон' },
        emitters: ['drip', 'glow'],
        fog: 0x2f5a60, ambient: 0.5,
        relics: ['bell', 'oar', 'pearl'],
    },
    fungal: {
        name: 'Грибная Чаща',
        floor: B.MOSS, floor2: B.DIRT, under: B.DIRT, under2: B.ROCK, wall: B.ROCK, inner: B.ROCK, rim: B.ROCK,
        path: 'root',
        places: [['grove', 5], ['mosscave', 2], ['camp', 1]],
        creatures: [['sporeling', 3], ['moth', 2], ['myconid', 3]],
        elite: { kind: 'myconid', name: 'Рыцарь Бледной Шляпки' },
        emitters: ['spore', 'glow'],
        fog: 0x3a2f55, ambient: 0.45,
        relics: ['lamp', 'crown', 'diary'],
    },
    crystal: {
        name: 'Хрустальные Жилы',
        floor: B.ROCK, floor2: B.MARBLE, under: B.ROCK, under2: B.CRYSTAL, wall: B.ROCK, inner: B.ROCK, rim: B.ROCK,
        path: 'crystal',
        places: [['geode', 5], ['camp', 1], ['mosscave', 1]],
        creatures: [['wisp', 3], ['cgolem', 3], ['bat', 2]],
        elite: { kind: 'cgolem', name: 'Колосс Призмы' },
        emitters: ['glint'],
        fog: 0x243a55, ambient: 0.45,
        relics: ['tear', 'prism', 'sky'],
    },
    crypt: {
        name: 'Катакомбы Безымянных',
        floor: B.CRYPT, floor2: B.TILE, under: B.ROCK, under2: B.CRYPT, wall: B.CRYPT, inner: B.CRYPT, rim: B.CRYPT,
        path: 'crypt',
        places: [['cryptHall', 4], ['chapel', 2], ['camp', 1], ['mosscave', 1]],
        creatures: [['skeleton', 4], ['ghost', 2], ['bat', 3]],
        elite: { kind: 'ghost', name: 'Безымянная Вдова' },
        emitters: ['dust'],
        fog: 0x2d2b3a, ambient: 0.4,
        relics: ['plaque', 'candle', 'skull'],
    },
    forge: {
        name: 'Кузня Глубинных',
        floor: B.METAL, floor2: B.BASALT, under: B.BASALT, under2: B.ROCK, wall: B.BRICK, inner: B.BASALT, rim: B.BASALT,
        path: 'metal',
        places: [['forgeHall', 4], ['lavaCave', 3], ['storage', 1], ['camp', 1]],
        creatures: [['imp', 3], ['salamander', 3], ['golem', 2]],
        elite: { kind: 'salamander', name: 'Мехоносец Угольный' },
        emitters: ['ember'],
        fog: 0x4a2a22, ambient: 0.45,
        relics: ['hammer', 'ingot', 'bellows'],
    },
    library: {
        name: 'Архив Тишины',
        floor: B.MARBLE, floor2: B.TILE, under: B.ROCK, under2: B.BRICK, wall: B.BRICK, inner: B.BOOKS, rim: B.BRICK,
        path: 'marble',
        places: [['stacks', 4], ['reading', 3], ['camp', 1]],
        creatures: [['book', 4], ['owl', 2], ['inkblot', 2]],
        elite: { kind: 'book', name: 'Том Последней Страницы' },
        emitters: ['dust'],
        fog: 0x3b3446, ambient: 0.5,
        relics: ['lastpage', 'quill', 'globe'],
    },
    roots: {
        name: 'Корни Мира',
        floor: B.MOSS, floor2: B.DIRT, under: B.DIRT, under2: B.BARK, wall: B.BARK, inner: B.ROCK, rim: B.BARK,
        path: 'root',
        places: [['rootCave', 5], ['grove', 1], ['camp', 1]],
        creatures: [['beetle', 3], ['thorn', 3], ['moth', 2]],
        elite: { kind: 'thorn', name: 'Садовник-Терновник' },
        emitters: ['spore', 'glow'],
        fog: 0x2c3a2a, ambient: 0.5,
        relics: ['seed', 'sap', 'staff'],
    },
    sanctum: {
        name: 'Врата Разреза',
        floor: B.MARBLE, floor2: B.TILE, under: B.ROCK, under2: B.CRYSTAL, wall: B.CRYPT, inner: B.MARBLE, rim: B.CRYPT,
        path: 'marble',
        places: [['gateHall', 1], ['antechamber', 1]],
        creatures: [['ghost', 1], ['skeleton', 1]],
        elite: null,
        emitters: ['glint', 'dust'],
        fog: 0x1d1830, ambient: 0.4,
        relics: ['firstring'],
    },
};
export const OUTDOOR = ['village', 'ruins'];
export const UNDERGROUND = ['mine', 'grotto', 'fungal', 'crystal', 'crypt', 'forge', 'library', 'roots'];

// ---- creatures
// temper: timid (flees), peaceful (ignores you), passive (fights back when hit),
// aggressive (attacks on sight), nocturnal (aggressive at night, timid by day),
// ranged (keeps distance and shoots), sleeper (sleeps until woken)
export const KINDS = {
    pigeon: { name: 'Голубь', temper: 'timid', hp: 1, dmg: 0, speed: 3.2, model: 'bird', color: 0x7fa6d9, size: 0.7, loot: [['coin', 0.5]] },
    crow: { name: 'Ворон', temper: 'timid', hp: 1, dmg: 0, speed: 3.4, model: 'bird', color: 0x2b2b33, size: 0.75, loot: [['coin', 0.6]] },
    sheep: { name: 'Овца', temper: 'peaceful', hp: 3, dmg: 0, speed: 1.2, model: 'sheep', color: 0xf1ede2, size: 1, loot: [['food', 0.8]] },
    slime: { name: 'Слизень', temper: 'passive', hp: 3, dmg: 1, speed: 1.3, model: 'slime', color: 0x8fd14f, size: 1, cd: 1.1, loot: [['coin', 0.8], ['potion', 0.2]] },
    wolf: { name: 'Волк', temper: 'nocturnal', hp: 4, dmg: 1, speed: 3.6, model: 'quad', color: 0x8d8f99, size: 1, aggro: 7, cd: 1.0, loot: [['food', 0.6], ['coin', 0.5]] },
    skeleton: { name: 'Скелет', temper: 'aggressive', hp: 4, dmg: 1, speed: 2.0, model: 'biped', color: 0xe9e2cf, size: 1, aggro: 6, cd: 1.2, loot: [['coin', 0.7], ['key', 0.08]] },
    ghost: { name: 'Призрак', temper: 'aggressive', hp: 4, dmg: 1, speed: 1.7, model: 'ghost', color: 0xeef5f3, size: 1, aggro: 7, cd: 1.4, fly: true, loot: [['coin', 0.7], ['potion', 0.2]] },
    bat: { name: 'Летучая мышь', temper: 'timid', hp: 1, dmg: 0, speed: 3.6, model: 'bat', color: 0x4a3f55, size: 0.7, fly: true, loot: [['coin', 0.4]] },
    rat: { name: 'Крыса', temper: 'timid', hp: 1, dmg: 0, speed: 3.4, model: 'rat', color: 0x7a6a5e, size: 0.6, loot: [['coin', 0.4]] },
    kobold: { name: 'Кобольд-шахтёр', temper: 'aggressive', hp: 3, dmg: 1, speed: 2.6, model: 'biped', color: 0xc66a3d, size: 0.8, aggro: 6, cd: 1.0, loot: [['coin', 1], ['gem', 0.25], ['key', 0.08]] },
    golem: { name: 'Кубоголем', temper: 'aggressive', hp: 6, dmg: 2, speed: 1.3, model: 'cube', color: 0x9b8f86, size: 1.1, aggro: 5, cd: 1.6, loot: [['gem', 0.5], ['coin', 0.6]] },
    frog: { name: 'Лягушка', temper: 'peaceful', hp: 2, dmg: 0, speed: 1.8, model: 'frog', color: 0x5fae5a, size: 0.8, loot: [['food', 0.5]] },
    crab: { name: 'Грот-краб', temper: 'passive', hp: 5, dmg: 1, speed: 1.6, model: 'crab', color: 0xd8603f, size: 0.9, cd: 1.2, loot: [['food', 0.6], ['gem', 0.15]] },
    drowned: { name: 'Утопленник', temper: 'aggressive', hp: 4, dmg: 1, speed: 1.7, model: 'biped', color: 0x7fae9e, size: 1, aggro: 6, cd: 1.3, loot: [['coin', 0.8], ['key', 0.08]] },
    sporeling: { name: 'Споровик', temper: 'passive', hp: 3, dmg: 1, speed: 1.2, model: 'shroom', color: 0xc56fd6, size: 0.8, cd: 1.3, loot: [['potion', 0.3], ['coin', 0.5]] },
    myconid: { name: 'Грибной рыцарь', temper: 'aggressive', hp: 5, dmg: 1, speed: 1.8, model: 'shroom', color: 0xe07b5a, size: 1.25, aggro: 6, cd: 1.3, loot: [['coin', 0.8], ['key', 0.08]] },
    moth: { name: 'Светляк-мотылёк', temper: 'timid', hp: 1, dmg: 0, speed: 2.4, model: 'moth', color: 0xfff1a8, size: 0.8, fly: true, glow: 0xfff1a8, loot: [['coin', 0.3]] },
    wisp: { name: 'Огонёк', temper: 'peaceful', hp: 2, dmg: 0, speed: 1.2, model: 'wisp', color: 0x9ff0ff, size: 0.8, fly: true, glow: 0x9ff0ff, loot: [['potion', 0.5]] },
    cgolem: { name: 'Хрустальный голем', temper: 'aggressive', hp: 8, dmg: 2, speed: 1.1, model: 'cube', color: 0x8fd8e8, size: 1.3, aggro: 5, cd: 1.7, loot: [['gem', 1]] },
    imp: { name: 'Бесёнок горна', temper: 'aggressive', hp: 3, dmg: 1, speed: 3.2, model: 'imp', color: 0xe0452e, size: 0.8, aggro: 7, cd: 0.9, loot: [['coin', 0.8]] },
    salamander: { name: 'Саламандра', temper: 'ranged', hp: 4, dmg: 1, speed: 1.8, model: 'lizard', color: 0xf09a2e, size: 1, aggro: 8, cd: 2.2, loot: [['coin', 0.8], ['gem', 0.2]] },
    book: { name: 'Летучий том', temper: 'aggressive', hp: 2, dmg: 1, speed: 2.6, model: 'book', color: 0x8a3b3b, size: 0.8, fly: true, aggro: 6, cd: 1.1, loot: [['coin', 0.6], ['key', 0.08]] },
    owl: { name: 'Сова-архивариус', temper: 'peaceful', hp: 2, dmg: 0, speed: 1.4, model: 'owl', color: 0xb58a5a, size: 0.9, loot: [['potion', 0.4]] },
    inkblot: { name: 'Клякса', temper: 'passive', hp: 3, dmg: 1, speed: 1.4, model: 'slime', color: 0x2a2440, size: 0.9, cd: 1.2, loot: [['coin', 0.8]] },
    beetle: { name: 'Корневой жук', temper: 'passive', hp: 4, dmg: 1, speed: 1.5, model: 'beetle', color: 0x3f6f4a, size: 0.9, cd: 1.2, loot: [['gem', 0.2], ['food', 0.4]] },
    thorn: { name: 'Терновник', temper: 'aggressive', hp: 4, dmg: 1, speed: 2.0, model: 'thorn', color: 0x6a8a3a, size: 1, aggro: 6, cd: 1.1, loot: [['coin', 0.7], ['key', 0.08]] },
    guardian: { name: 'Страж Врат', temper: 'aggressive', hp: 18, dmg: 2, speed: 1.6, model: 'biped', color: 0x5a5f7a, size: 1.6, aggro: 7, leash: 8, cd: 1.5, loot: [['heart', 1]] },
};

export const ITEMS = {
    coin: { name: 'монета' },
    gem: { name: 'самоцвет', value: 5 },
    potion: { name: 'зелье' },
    food: { name: 'еда' },
    key: { name: 'ключ' },
    seal: { name: 'Печать Разреза' },
    heart: { name: 'сердце' },
    sword: { name: 'клинок острее' },
    relic: { name: 'реликвия' },
};

export const SHOP = [
    { item: 'potion', price: 8, name: 'Зелье (+3 сердца)' },
    { item: 'heart', price: 30, name: 'Сердце (+1 к запасу)' },
    { item: 'sword', price: 40, name: 'Заточка клинка (+1 к удару)' },
];

// ---- relics: one of a kind, collected into the codex
export const RELICS = {
    vane: { biome: 'village', name: 'Флюгер-петух', text: 'Всегда показывает вниз. Старики говорят: ветер здесь дует из-под земли.' },
    spoon: { biome: 'village', name: 'Ложка бабушки Ольхи', text: 'Этой ложкой мешали суп, когда мир треснул. Суп не пролился.' },
    map: { biome: 'village', name: 'Первая карта Разреза', text: 'Нарисована углём на двери сарая. Ярусы пронумерованы сверху вниз, последний подписан: «не ходи».' },
    helm: { biome: 'ruins', name: 'Шлем без забрала', text: 'Страж, носивший его, смотрел в Разрез сорок лет и ни разу не моргнул.' },
    horn: { biome: 'ruins', name: 'Сломанный горн', text: 'Трубил тревогу, когда из глубины поднялось первое чудище. Трубит до сих пор, если приложить ухо.' },
    oath: { biome: 'ruins', name: 'Присяга на камне', text: '«Держать край, пока край держит нас». Ниже процарапано: «край устал».' },
    helmet: { biome: 'mine', name: 'Каска с огарком', text: 'Шахтёр Грод спустился на семь ярусов ниже, чем разрешали. Вернулась только каска.' },
    pick: { biome: 'mine', name: 'Кирка, погнутая о кость', text: 'Внутри горы нашли ребро размером с мост. Кирка не выдержала первой.' },
    token: { biome: 'mine', name: 'Жетон тринадцатой смены', text: 'Тринадцатой смены никогда не было. Жетон тёплый.' },
    bell: { biome: 'grotto', name: 'Колокол утонувшего причала', text: 'Звонит под водой по средам. Рыбы собираются слушать.' },
    oar: { biome: 'grotto', name: 'Весло без лодки', text: 'Лодочник Мирон уплыл по подземной реке вниз. Весло вернулось против течения.' },
    pearl: { biome: 'grotto', name: 'Жемчужина-глаз', text: 'Смотрит на того, кто её держит, и иногда моргает.' },
    lamp: { biome: 'fungal', name: 'Споровая лампа', text: 'Светит, пока ей рассказывают сказки. Молчание гасит её за минуту.' },
    crown: { biome: 'fungal', name: 'Корона Короля-Гриба', text: 'Король правил триста лет и ни разу не сдвинулся с места.' },
    diary: { biome: 'fungal', name: 'Дневник ботаника Эльзы', text: 'Последняя запись: «Они растут, когда на них смотришь».' },
    tear: { biome: 'crystal', name: 'Слеза кристалла', text: 'Кристаллы здесь плачут раз в сто лет. Этой слезе — девяносто девять.' },
    prism: { biome: 'crystal', name: 'Призма эха', text: 'Повторяет то, что ты скажешь завтра.' },
    sky: { biome: 'crystal', name: 'Осколок неба', text: 'Упал сюда, когда меч пробил небесный свод. На нём до сих пор видна звезда.' },
    plaque: { biome: 'crypt', name: 'Табличка без имени', text: 'Здесь хоронили тех, чьи имена забрал Разрез. Табличек больше, чем могил.' },
    candle: { biome: 'crypt', name: 'Свеча, что не тает', text: 'Её зажгли в день раскола. Пламя холодное.' },
    skull: { biome: 'crypt', name: 'Череп со счётами', text: 'Счетовод Безымянных продолжает считать после смерти. Сальдо всегда отрицательное.' },
    hammer: { biome: 'forge', name: 'Молот-наковальня', text: 'Гномы ковали им мост через Разрез. Мост до сих пор не закончен — и не упал.' },
    ingot: { biome: 'forge', name: 'Слиток звёздного железа', text: 'Из такого металла был выкован меч, что сразил бога.' },
    bellows: { biome: 'forge', name: 'Мех с дыханием дракона', text: 'Если сжать — пахнет серой и старыми обидами.' },
    lastpage: { biome: 'library', name: 'Книга с последней страницей', text: 'Все страницы вырваны, кроме последней: «и тогда они спустились».' },
    quill: { biome: 'library', name: 'Перо летописца', text: 'Пишет само, если оставить его на ночь. По утрам в летописи новые ярусы.' },
    globe: { biome: 'library', name: 'Глобус изнутри', text: 'Мир на нём — полая сфера, и все живут на внутренней стороне.' },
    seed: { biome: 'roots', name: 'Семя мирового древа', text: 'Корни этого дерева держат ярусы вместе, как нитки — лоскутное одеяло.' },
    sap: { biome: 'roots', name: 'Светящийся сок', text: 'Говорят, это кровь бога, впитанная корнями.' },
    staff: { biome: 'roots', name: 'Посох садовника', text: 'Садовник подрезал корни, чтобы ярусы не срослись обратно. Зачем — не записано.' },
    firstring: { biome: 'sanctum', name: 'Первое кольцо Врат', text: 'Врата ставили до того, как мир раскололся. Строители знали.' },
};

// names for notes on campfires and signposts
export const WANDERERS = ['Грод', 'Эльза', 'Мирон', 'Ольха', 'Тамас', 'Бьянка', 'Кирилл', 'Нора', 'Ян', 'Сивка', 'Лука', 'Рада'];
export const NOTES = [
    '{n}: «Ниже этого яруса лестницы строили не люди».',
    '{n}: «Если слышишь колокол снизу — не отвечай».',
    '{n}: «Печати не любят спешки. Их держат те, кто сильнее тебя».',
    '{n}: «Ночью волки смелеют. Днём бегут от тени».',
    '{n}: «Вода внизу глубокая — прыгай, не бойся».',
    '{n}: «Рычаги в стенах скрипят к открытым воротам».',
    '{n}: «Здесь я разжёг костёр. Посиди — полегчает».',
    '{n}: «Слизни не злые. Пока их не тронешь».',
    '{n}: «Торговец берёт монеты и самоцветы. Больше ничего ему не нужно».',
    '{n}: «Я видел Врата. Они смотрели на меня».',
];
